### ISSUE TITLE
SensioFrameworkExtraBundle

### ISSUE THREAD

**Issue by skydiablo** [driftphp/http-kernel#38]
it seems, the bundle handling is a little bit wired :S ? i have try to install the SensioFrameworkExtraBundle via compser (symfony/flex is also installed) but without success... some of the default behavior for extension handling is changed by drift. how should i install these old good bundle "SensioFrameworkExtraBundle" ?

**Comment by mmoreram** [comment]
@skydiablo what do you mean a bit weird? you can install this bundle the same way you do in Symfony.

- Adding it into composer
- Composer update
- Add the bundles into the array of bundles
- Add the bundle configuration inside the services.yml

**Comment by skydiablo** [comment]
okay, this was hard but i actually find it. drift dispatch the necessary kernel events without the needed event-names, checkout this PR: https://github.com/driftphp/http-kernel/pull/39

on the other hand, the drift server isnt loading bundles like symfony is expect it (auto config by symfony/flex). so i have to change the drift `bundles.php` to:

```
return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    \Drift\DBAL\DBALBundle::class => ['all' => true],
] + require(__DIR__.'/../../config/bundles.php'); // load symfony default location bundles.php
```
and also load packages config by my own, so i add at drift `service.yml`:

```
imports:
  - { resource: ../../config/packages/*.yaml }
```

i know, drift follow his own rules of path recommendations but just install a symfony bundles via composer isnt follow the default way. so some changes are needed (see above).

**Comment by mmoreram** [comment]
PR merged.
Good catch!

Thanks!
